### ISSUE TITLE
Trap

### ISSUE THREAD

**Issue by Tellie** [komh/git-os2#5]
Hello
When using git push i get the following trap...

H:\git\whois-os2>git push

Killed by SIGSEGV
pid=0x00ad ppid=0x00ac tid=0x0001 slot=0x00a6 pri=0x0200 mc=0x0001 ps=0x0010
H:\USR\LOCAL1220\LIBEXEC\GIT-CORE\GIT-REMOTE-HTTP.EXE
cs:eip=0000:00000000      ss:esp=0043003b:004c004c      ebp=00320053
 ds=00320053      es=0000      fs=003a0043      gs=0000     efl=00410054
eax=002ef930 ebx=1ffc9d7c ecx=002ef944 edx=002ef968 edi=0053005c esi=002eff5c
Creating 00AD_01.TRP
Moved 00ad_01.TRP to C:\var\log\app\64061e36-00ad_01-GIT-REMOTE-HTTP-exceptq.txt

I try to set   GIT_USE_NPIPE=Y but that din't help

When i use the Git-remote-http from earlyer build all works
Please remove the CCache one...

[64031451-2
[64061f28-00b1_01-GIT-REMOTE-HTTP-exceptq.txt](https://github.com/komh/git-os2/files/10900357/64061f28-00b1_01-GIT-REMOTE-HTTP-exceptq.txt)
b76_01-CCACHE-exceptq.txt](https://github.com/komh/git-os2/files/10900287/64031451-2b76_01-CCACHE-exceptq.txt)

**Comment by komh** [comment]
Hi/2.

I've cloned your repo and pushed a commit, but I have no problems at all.

Anyway, I attach debug build for git-remote-http.exe. Please attach the output.

[git-remote-http.zip](https://github.com/komh/git-os2/files/10906432/git-remote-http.zip)

**Comment by Tellie** [comment]
Hi
I attach log

Killed by SIGSEGV
pid=0x0057 ppid=0x0056 tid=0x0001 slot=0x007d pri=0x0200 mc=0x0001 ps=0x0010
H:\USR\LOCAL1220\LIBEXEC\GIT-CORE\GIT-REMOTE-HTTP.EXE
cs:eip=0000:00000000      ss:esp=003b005c:003a0043      ebp=004e0053
 ds=00590053      es=0000      fs=0053004f      gs=0000     efl=003b004c
eax=002ef930 ebx=1ffc9d7c ecx=002ef944 edx=002ef968 edi=00540053 esi=002eff5c
Creating 0057_01.TRP
Moved 0057_01.TRP to C:\var\log\app\64077b39-0057_01-GIT-REMOTE-HTTP-exceptq.txt
[64077b39-0057_01-GIT-REMOTE-HTTP-exceptq.txt](https://github.com/komh/git-os2/files/10911993/64077b39-0057_01-GIT-REMOTE-HTTP-exceptq.txt)

**Comment by komh** [comment]
Very strange. Exceptq shows NULL-passed to strdup(), however it was a constant string. That is, it cannot be NULL.

Can you show me your env. vars ? That is, the result of ```set``` command.

Meanwhile, I've disabled some utf-8 features. Test please...

[git-remote-http.zip](https://github.com/komh/git-os2/files/10921850/git-remote-http.zip)

**Comment by Tellie** [comment]
Hi
Also this exe file traps...

I attach set cmd 
[set-2023030817245156.log](https://github.com/komh/git-os2/files/10922751/set-2023030817245156.log)

**Comment by komh** [comment]
I'm afraid I could not find any errors with your env vars.

How do you provide your credential to a server ? Just type ? or helper ?

I would suggest to 

1. just type your credential if not.
2. set HOME to a new directory

**Comment by Tellie** [comment]
Hi Ko
I manually fill in the name and pass

Set home i try later to a other dir

Op zo 12 mrt. 2023 12:33 schreef KO Myung-Hun ***@***.***>:

**Comment by Tellie** [comment]
Hi Ko
Sorry for the long delay..
But i solve this issue
I had same crashes with v2.42.0
So i use a empty home dir like you're suggested
And there i saw no crashes.
i put back my gitconfig and the crashes where back. i deleted the gitconfig and make a new one i see no more crashes.
Only i see........
C:\FC-1220>git --version
warning: $GIT_FIND is not defined. Assume C:/usr/bin/find.
warning: $GIT_SORT is not defined. Assume C:/usr/bin/sort.
git version 2.42.0

I thought the warnings where fixed long time ago?
So sorry for the noise ....

**Comment by komh** [comment]
Oh, good!

And you should set GIT_FIND and GIT_SORT env. var. to your GNU find and sort utils, respectively.

Thanks!
